final Map<String, Map<String, String>> countryCodes = {
  "+49": {"name": "Deutsch", "flag": "🇩🇪"},
  "+90": {"name": "Türkisch", "flag": "🇹🇷"},
  //"+1": {"name": "Amerikanisch", "flag": "🇺🇸"},
  "+44": {"name": "Englisch", "flag": "🇬🇧"},
  "+34": {"name": "Spanisch", "flag": "🇪🇸"},
  "+39": {"name": "Italienisch", "flag": "🇮🇹"},
  "+48": {"name": "Polnisch", "flag": "🇵🇱"},
  "+33": {"name": "Französich", "flag": "🇫🇷"},
  "+32": {"name": "Belgisch", "flag": "🇧🇪"},
  // "+31": {"name": "Niederländisch", "flag": "🇳🇱"},
  // "+420": {"name": "Tschechien", "flag": "🇨🇿"},
  // "+36": {"name": "Ungarn", "flag": "🇭🇺"},
  // "+380": {"name": "Ukraine", "flag": "🇺🇦"},
  // "+359": {"name": "Bulgarien", "flag": "🇧🇬"},
  // "+40": {"name": "Rumänien", "flag": "🇷🇴"},
  // "+381": {"name": "Serbien", "flag": "🇷🇸"},
  // "+385": {"name": "Kroatien", "flag": "🇭🇷"},
  // "+387": {"name": "Bosnien", "flag": "🇧🇦"},
  // "+30": {"name": "Griechenland", "flag": "🇬🇷"},
  // "+212": {"name": "Marokko", "flag": "🇲🇦"},
  // "+216": {"name": "Tunesien", "flag": "🇹🇳"},
};
