final Map<String, Map<String, String>> countryCodes = {
  "+49": {"name": "Deutschland", "flag": "🇩🇪"},
  "+90": {"name": "Türkei", "flag": "🇹🇷"},
  "+1": {"name": "USA", "flag": "🇺🇸"},
  "+44": {"name": "United Kingdom", "flag": "🇬🇧"},
  "+34": {"name": "Spanien", "flag": "🇪🇸"},
  "+39": {"name": "Italien", "flag": "🇮🇹"},
  "+48": {"name": "Polen", "flag": "🇵🇱"},
  "+33": {"name": "Frankreich", "flag": "🇫🇷"},
  "+32": {"name": "Belgien", "flag": "🇧🇪"},
  "+31": {"name": "Niederlande", "flag": "🇳🇱"},
  "+420": {"name": "Tschechien", "flag": "🇨🇿"},
  "+36": {"name": "Ungarn", "flag": "🇭🇺"},
  "+380": {"name": "Ukraine", "flag": "🇺🇦"},
  "+359": {"name": "Bulgarien", "flag": "🇧🇬"},
  "+40": {"name": "Rumänien", "flag": "🇷🇴"},
  "+381": {"name": "Serbien", "flag": "🇷🇸"},
  "+385": {"name": "Kroatien", "flag": "🇭🇷"},
  "+387": {"name": "Bosnien", "flag": "🇧🇦"},
  "+30": {"name": "Griechenland", "flag": "🇬🇷"},
  "+212": {"name": "Marokko", "flag": "🇲🇦"},
  "+216": {"name": "Tunesien", "flag": "🇹🇳"},
};
